### ISSUE TITLE
I'm having issue with the power of my computer.

### ISSUE THREAD

**Issue by Broodierchip** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#11]
The computer is not charging, it will charge then stop . Everything else is working. Then new update file did fix the touchpad and the brightness.

**Comment by balopez83** [comment]
@Broodierchip So the "fix" to enable battery power management features also makes macOS think it can start and stop charging of the battery. If you are seeing a plug icon (not the lightning bolt) it should actually still be charging and if you wait it should increase percentage over time. You can tell macOS to "charge" which give you the lightning bold by clicking the battery icon and telling it to charge from the drop-down menu. In the end it is only cosmetic as either way it should be charging. 

Let me know if this resolves it or if the issue is still happening. More than likely if you are actually having a charging issue it would be a hardware related issue as macOS doesn't have the ability to control charging like that on the Surface devices and I don't believe Surface devices ever had the ability to actively start and stop charging even in Windows (except for the 50% limit that can be imposed via UEFI).
