### ISSUE TITLE
YouTube playing problem

### ISSUE THREAD

**Issue by rkinlen** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#18]
When I try to play YouTube it just loads for ages and then slows down the whole laptop and then I have to restart. Is there any fix?

**Comment by balopez83** [comment]
@rkinlen I need a bit more information. What is your OS version, computer specs, browser used, and EFI release version?

If you're using Safari I would attempt the same with chrome or other browser. Firefox has a lot of issues though some beta/dev versions work better than others though ymmv.

**Comment by rkinlen** [comment]
It is a surface book gen 1, safari on Ventura.

**Comment by balopez83** [comment]
@rkinlen What EFI release version are you using? There have been a lot of changes in the recent EFIs and so it will help me troubleshoot.

**Comment by balopez83** [comment]
@rkinlen This issue is actually the same as issue #17 and is related to kabylake graphics spoofing when these are skylake machines. Unfortunately programming this as skylake causes kernel panics and prevents booting. I am working on this though not sure if this will be fixable. 

In the interim I would recommend using chrome or other chromium based browser as it does appear to work better since they use software rendering and DRM. Safari uses hardware rendering and DRM which combined with the less than perfect spoofing is causing the massive slowdown.

**Comment by balopez83** [comment]
@rkinlen I actually think I may be close to resolving this issue.

**Comment by balopez83** [comment]
@rkinlen This issue has now been resolved with Release 10.0.0.
Please make sure to reset NVRAM with this update or you may continue to have issues. If issues continue to persist you may need to reinstall macOS though that should not be needed.
