### ISSUE TITLE
Dual booting windows

### ISSUE THREAD

**Issue by rkinlen** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#20]
I have a surface book gen 1, with the latest released.
I have install windows installer on a SD card, when I try and boot it gives me this error. “LoadImage failed - access denied”
I have checked the post install guide and enabled. “ UEFI -> Quirks -> DisableSecurityPolicy”.

I had also disabled secure boot on the BIOS.

Thanks very much.

**Comment by balopez83** [comment]
Hi @rkinlen as far as I am aware the issues you are having is a Surface issue specifically. For some reason Microsoft restricts booting from an SD card on the SP4 and Surface Book gen1 which is why OpenCore is throwing that error. I believe you are able to boot from an SDcard plugged into a USB adapter much like booting the installer from a traditional USB drive

**Comment by rkinlen** [comment]
Ok thanks I will try

**Comment by balopez83** [comment]
Assuming this issue is resolved and so closing. You may re-open if you have additional questions on this item.
