### ISSUE TITLE
About Surface Pro 7

### ISSUE THREAD

**Issue by bilaleminturker06** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#22]
Hello i am using your efi files for surface pro 7. everthing works except sleep. when it is goes to sleep it not wake if i use Gprw patch. I am not using GPRW patch so it restart when waking sleep. can you help me about this.thanks

**Comment by bilaleminturker06** [comment]
[EFI.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/13528330/EFI.zip)
it is my efi file without airport and intelbtfirmware kext. (because of file size)

**Comment by balopez83** [comment]
@bilaleminturker06 I don't have a Surface Pro 7 to test with so I cannot help much unfortunately. 

Using a Surface Pro 4 EFI on a 7 is not going to work well unfortunately and you're going to miss key features that will actually work. You also run the risk of damaging your SP7 as the Skylake 6xxx generation CPU/gpu are about as different from the Surface Pro's 10th gen CPU/gpu as the stone wheel to a jet engine.

Specifically your sleep/wake issue is likely an issue due to improper power management settings as the cpu generation this EFI is set for by default is completely different. Most likely your computer can't wake up because it doesn't know how to with this EFI. 

Alternatively, it is also possible that you forgot to change your power management settings when using the gprw patching. It requires Hibernatemode 25 where by default it's set to 3. A setting of 3 means your computer will try to sleep but fail to sleep and instead have a black screen in high processor mode. In this case it always requires holding the power button to reset the device. This issue impacts all Surface generations and assuming this is the reason your sleep isn't working I still highly recommend switching to the proper SP7 repo to avoid other issues or damage and to have more support for your computer. 

You should be using the repo linked below for the SP7. It should provide better support including proper graphics with no glitching, built in WiFi support which mine would not, sleep support as well. It does look like that repo is losing some support so you may need to update OpenCore and the kexts but it should still give you a better starting point. 

https://github.com/badstorm/surface-pro-7-opencore

I would highly recommend switching to the OpenIntel WiFi kext as it looks like the repo is using the ones that require a client where the openintel ones work with Apples native built in WiFi control. See link below:

https://github.com/OpenIntelWireless/itlwm

And finally, make sure that you use the latest BigSurface kext and the ipts software to enable full touch and pen support: 

https://github.com/Xiashangning/BigSurface

**Comment by balopez83** [comment]
@bilaleminturker06 A third possible direction you could look to fix sleep but it should be used as a absolute last result or you can break things is to use the link below for additional patching. You would want to look at the items for sleep patching as there is a lot of other information in the linked repo.

https://github.com/5T33Z0/OC-Little-Translated

**Comment by bilaleminturker06** [comment]
@balopez83 Thanks you very much for your reply. 

https://github.com/badstorm/surface-pro-7-opencore
i use this efi. thanks to @badstorm.  this is works expect sdcard reader and sleep. I solve sdcard problem with usbmap. I can not solve sleep issue. The computer on which I use this file does not go into deep sleep and the battery runs out very quickly. That's why I wanted to adapt your file and use it, but it didn't work. 

I will also review the files you sent and try to solve the sleep problem. Thank you very much again

**Comment by billabongbruno** [comment]
> @balopez83 Thanks you very much for your reply. 
> 
> https://github.com/badstorm/surface-pro-7-opencore
> i use this efi. thanks to @badstorm.  this is works expect sdcard reader and sleep. I solve sdcard problem with usbmap. I can not solve sleep issue. The computer on which I use this file does not go into deep sleep and the battery runs out very quickly. That's why I wanted to adapt your file and use it, but it didn't work. 
> 
> I will also review the files you sent and try to solve the sleep problem. Thank you very much again

I have no idea which processor variant you have, but have you tried here?
https://github.com/Xiashangning/SurfacePro7Opencore

**Comment by balopez83** [comment]
@bilaleminturker06 I think I misunderstood and thought you were using the SP4 EFI directly. So I can take a look later. There are generally just two DSDT patches and the GPRW ssdt needed plus changing Hibernatemode and a few other power management settings as is in my quirks and fixes page linked in my readme to get "sleep" working. Technically it's more of a hibernation not sleep as sleep will never work the way it's supposed to on any Surface but it's better than the black screen and fast power drain.

Your follow up message tells me that you have the issue where the screen goes off and it simply never enters sleep which is why you can't wake it and your battery still drains. 

If you have the time before I can actually look at it you can simply re enable the gprw patches and go to my quirks page and apply all the power management commands in terminal. It should fix your issue.

**Comment by balopez83** [comment]
@bilaleminturker06 So at first glance you will still have a fair amount of issues using this config that are going to cause you problems. I looked at both of the SP7 repos and they are closer but also need some changes too. I am going to try and create a new config that "should" work though may need some trial and error to get it exactly right. I do need to know which CPU your SP7 is?

**Comment by balopez83** [comment]
@bilaleminturker06 Try this EFI. This has taken the existing SP7 repos and pulled the good stuff out of each while dumping all the incorrect stuff. I have added back in the GPRW patching which means you must do the power management settings changes as listed in my [quirks page](https://github.com/balopez83/Surface_Pro_3_Hackintosh/blob/main/3-quirks%26fixes.md) item number 4. 

I did change the SMBIOS to MacBookPro16,2 as it is better aligned with the CPU inside a Surface Pro. MacBook Air SMBIOS's tend to have lower power scaling which can cause instability on the higher performance CPU's in the Surface Pro's. If you had any iServices signed in you will need to sign out or you will have problems. 

Let me know if this works for you and if you have any issues. I forgot my work computer is a Surface Pro 7, so I may just add a new repo for the SP7 going forward since it seems the other two haven't been updated in quite some time. I haven't personally tested this EFI so expect I might have missed something and it might not work the first time you try to boot so keep a backup of your last working EFI in case you need something to get you booted. 

Oh and last thing, you will need to add back in the Intel Wifi and Bluetooth kexts before booting as they are not included in this EFI due to size. I did update all the kexts in this EFI so it should be almost perfect at this point.
[EFI.zip](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/files/13530989/EFI.zip)

**Comment by balopez83** [comment]
I created a new repo for the Surface Pro 7 though its not fully up to date with everything yet. To keep the SP4 repo clean lets move the issue to that repo. 

https://github.com/balopez83/Surface-Pro-7-Hackintosh/tree/main

As soon as I can, I will try to get a fully running and tested EFI uploaded into the releases.

**Comment by balopez83** [comment]
I created a new repo for the Surface Pro 7 though its not fully up to date with everything yet. To keep the SP4 repo clean lets move the issue to that repo. 

https://github.com/balopez83/Surface-Pro-7-Hackintosh/tree/main

As soon as I can, I will try to get a fully running and tested EFI uploaded into the releases.

**Comment by balopez83** [comment]
@bilaleminturker06 I have posted an update to the EFI I linked earlier on my new SP7 repo page. Should get you a little further as it fixes an error in my earlier EFI and adds the Wifi and Bluetooth kexts for Sonoma only so far. I am actively testing macOS on an SP7 right now so might have some updates to the EFI posted there soon.

**Comment by bilaleminturker06** [comment]
Thank you very much for your help. I am closing this issue so that the sp4 repo is clean. I will try your work on the SP7 repo. Thank you very much again. you are a very beautiful person
