### ISSUE TITLE
No installation option

### ISSUE THREAD

**Issue by Giant-Li** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#23]
I created a Sonoma(14.5) USB installation disk with Etcher, and copied the EFI files as instructed on a win11 PC。
When plugged to my Surface pro 4 (i5/8G/256G), the USB disk can boot the system properly, but showed  only windows option while no installation option. I have renamed the _config-SurfacePro4-i3&i5.plist_ to _config.plist_.
![微信图片_20240606162923](https://github.com/balopez83/Surface_Pro_4_and_Surface_Book_Hackintosh/assets/84618443/3ae174d6-bdb3-481c-a590-b3bc9bb9aef5)

**Comment by balopez83** [comment]
@Giant-Li You likely need to hit the space bar at that screen to have OpenCore show the "recovery" options. 

I am not aware of a reliable way to create a macOS installer in windows except through a virtual machine of MacOS or using a real Mac. Saying that, the reason you may be seeing no installer could be because you have a web recovery and not a full installer.

You should confirm that your installer is about 14gb in size. If it's much smaller the issue you're having is that you have a web installer and not the full installer. Usually a full installer will show up in the menu which is why I suspect you have the wrong one.

**Comment by billabongbruno** [comment]
> @Giant-Li You likely need to hit the space bar at that screen to have OpenCore show the "recovery" options.
> 
> I am not aware of a reliable way to create a macOS installer in windows except through a virtual machine of MacOS or using a real Mac. Saying that, the reason you may be seeing no installer could be because you have a web recovery and not a full installer.
> 
> You should confirm that your installer is about 14gb in size. If it's much smaller the issue you're having is that you have a web installer and not the full installer. Usually a full installer will show up in the menu which is why I suspect you have the wrong one.

Hey there.

As per creating a reliable installer under Windows, I have a solution, which is the one I use.

I get a clean .raw macOS image file (can't link it here, just google Olarila) and then proceed to burn it to a USB using Balena Etcher.

After that, simply run any program (MiniTool Partition Wizard, for example) that will show the hidden EFI partition and replace the present EFI folder with yours (with Explorer++, for example).

(Or use TransMac and edit the .raw file, but that is waaaaaaay harder).


Hope this helps.


Best regards,
Bruno.

**Comment by Giant-Li** [comment]
My original install image is a .dmg file and has a size of 13,684,964,373 bytes. I think it should be a full installer. I burn it to a USB with Balena Etcher in a Win11 PC. The process goes properly(burn and verification). Then I open the USB with Disk Genius and copy the EFI folder to the EFI partition(renamed the config-SurfacePro4-i3&i5.plist to config.plist). And I can see the disk image partition in Disk Genius which has a Mac OS X Apple APFS file system and a size of 14.2GB. 
During installation, at the selecting screen I hit the space bar and i get several exec options, such as openshell.efi, chiptune.efi, etc. except installation option.
I have turned off the Securityboot in UEFI settings and it turned out to be no help. I'm still trying and have no idea where is wrong.

Thank you guys!

Best wishes,
Li

**Comment by balopez83** [comment]
@Giant-Li The size should be correct for the full installer so you should be good there.

I could be wrong but I think the issue is that your disk is formatted APFS and not HFS+ 

It could also simply be that the program never properly copied the installer to the disk. On a Mac you typically use terminal to create a disk and it uses files within the installer to create a boot disk instead of the disk image as is. 

Personally I think it's because the format for installers is supposed to be HFS+. 

While OpenCore reads APFS, I don't think an installer copied to an APFS drive is actually capable of being booted which means despite validating the files copied, the software didn't actually make it properly bootable. 

Hope it's just the format and you can get up and running.

**Comment by balopez83** [comment]
@Giant-Li were you able to resolve this issue?

**Comment by Giant-Li** [comment]
> @Giant-Li were you able to resolve this issue?

I'm sorry.
After several attempts, I still can't finish the installation with this EFI. Then I changed to install bigsur with EFI from this repo https://github.com/icaros7/OpenCore_Surface_Pro_4. ( I'v successfully installed bigsur with the EFI two years ago, so I know it works)
So, I had no idea whether it was due to the image or the EFI files.

Regards

**Comment by balopez83** [comment]
@Giant-Li I'm not sure honestly though it could be as simple as having the windows folder on your EFI usb. While you need to keep it to dual boot on you don't want it on the USB. 

By default the EFI hides what it thinks is a recovery. I don't have much ability to test the SP7 regularly so it is hard to troubleshoot this one but when I have time I can. My recommendation would be to use your old usb to install for now and then switch to my EFI after install. The icaros one is a bit old and based off another efi that is similar so is missing some of the fixes in my EFI. 

As I have time though I will see if I can duplicate your issue. Once you have macOS installed you may want to also make a new updated installer using my EFI the macOS way and see if that works better. It could just be something in the way Windows talks to the usb that could be causing the issues you're seeing

**Comment by balopez83** [comment]
@Giant-Li feel free to try again with the latest EFI. There are some key changes that may improve or resolve your issue.

**Comment by Giant-Li** [comment]
Hello, I'm back to say thank you! The latest version works perfect for me! Solved the boot and restart issue.
