### ISSUE TITLE
Secure Boot On with OpenCore

### ISSUE THREAD

**Issue by mxg1231** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#4]
Error reporting using Secure Boot On with OpenCore:oc failed to load configuration.How to deal with it, thank you

**Comment by balopez83** [comment]
Hi @mxg1231 please see "chapter 7" link on the main readme. That has all the steps to enable secure boot. 

Important: make sure to turn off secure boot in UEFI first before booting and if you have windows installed you may need to rename the Microsoft folder in your EFI otherwise you won't see the boot options to enroll the key. 
The boot option for your key will be named the same as your EFI drive.
Once secure boot is off you can follow from step 3 in the instructions

**Comment by balopez83** [comment]
If this resolves your issues please go ahead and close this issue

**Comment by mxg1231** [comment]
First rename the Microsoft folder in EFI,Secure Boot Enabled successfully,Thank you very much.
