### ISSUE TITLE
oc start win10 issue

### ISSUE THREAD

**Issue by mxg1231** [balopez83/Surface-Pro-4-and-Surface-Book-Hackintosh#5]
Found a problem after oc start win10, can not modify the boot item, how to solve this? thank you

**Comment by balopez83** [comment]
I am not clear what you are asking. Modifying OC boot items from Windows is challenging but can be done by mounting the EFI partition from a command prompt using "Diskpart" commands. From there you would need to use "ProperTree" downloadable from Github to edit the config.plist for OC. 

If your issue is related to booting back to macOS I would suggest simply creating a new "Fat32" formatted usb and placing the EFI folder on it where you can edit it more easily. Booting with the usb until you have your settings set properly will avoid other possible issues. Once you have it set the way you like you can then copy that EFI to your SSD.

**Comment by mxg1231** [comment]
oc boot into win10, can not be in the win interface with the help of software modification after the next restart, through that way to start. Only change it in UEFI.
